all:Ex3q1 Ex3q2a Ex3q2b Ex3q3a Ex3q3b
Ex3q1: Ex3q1.c
    gcc Ex3q1.c -o Ex3q1

Ex3q2a: Ex3q2a.c
    gcc Ex3q2a.c -o Ex3q2a

Ex3q2b: Ex3q2b.c
    gcc Ex3q2b.c -o Ex3q2b

Ex3q3a: Ex3q3a.c
    gcc Ex3q3a.c -o Ex3q3a -lpthread

Ex3q3b: Ex3q3b.c
    gcc Ex3q3b.c -o Ex3q3b -lpthread


